encoding: UTF-8
title: えも？
description: EMOTE with GHOST
github:
  repository_url: null
  is_user_page: null
  is_project_page: null
kramdown:
  input: GFM
  hard_wrap: true
future: true
jailed: false
theme: jekyll-theme-leap-day
#theme: jekyll-theme-primer
gfm_quirks: paragraph_end